//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupDocs_Viewer_SharePoint.Layouts.GroupDocs_Viewer_SharePoint {
    
    
    public partial class @default {
    }
}
